<?php

return array(
	'bulk_delete'		=> 'Confirm Bulk Delete Assets',
  'bulk_delete_help'	=> 'Review the assets for bulk deletion below. Once deleted, these assets can be restored, but they will no longer be associated with any users they are currently assigned to.',
  'bulk_delete_warn'	=> 'You are about to delete :asset_count assets.',
	'bulk_update'		=> 'Bulk Update Assets',
	'bulk_update_help'	=> 'This form allows you to update multiple assets at once. Only fill in the fields you need to change. Any fields left blank will remain unchanged. ',
	'bulk_update_warn'	=> 'You are about to edit the properties of :asset_count assets.',
    'checkedout_to'		=> 'Checked Out To',
    'checkout_date'		=> 'Checkout Date',
    'checkin_date'		=> 'Checkin Date',
    'checkout_to'		=> 'Checkout to',
    'cost'				=> 'Purchase Cost',
    'create'			=> 'Create Asset',
    'date'				=> 'Purchase Date',
    'depreciation'	    => 'Depreciation',
    'depreciates_on'	=> 'Depreciates On',
    'default_location'	=> 'Default Location',
    'eol_date'			=> 'EOL Date',
    'eol_rate'			=> 'EOL Rate',
    'expected_checkin'  => 'Expected Checkin Date',
    'expires'			=> 'Expires',
    'fully_depreciated'	=> 'Fully Depreciated',
    'help_checkout'		=> 'If you wish to assign this asset immediately, select "Ready to Deploy" from the status list above. ',
    'mac_address'		=> 'MAC Address',
    'manufacturer'		=> 'Manufacturer',
    'model'				=> 'Model',
    'months'			=> 'months',
    'name'				=> 'Building Name',
    'stock_holder_code' => 'Stock Holder Code',
    'description' => 'Building Description',
    'revenue_village' => 'Revenue Village',
    'dimension' => 'Dimension',
    'no_of_floor' => 'No Of Floor',
    'year_of_acquisition' => 'Year Of Acquisition',
    'improvement' => 'Improvement',
    'life_of_assets' => 'Life Of Assets',
    'no_of_years_assets_use' => 'No of Years Use',
    'remaining_life' => 'Remaining Life',
    'rate_of_depreciation' => 'Rate Of Depreciation',
    'currunt_use_of_building' => 'Currunt Use Of Building',
    'remarks' => 'Remarks',    
    'notes'				=> 'Notes',
    'order'				=> 'Order Number',
    'qr'				=> 'QR Code',
    'requestable'		=> 'Users may request this asset',
    'select_statustype'	=> 'Select Status Type',
    'serial'			=> 'Serial',
    'status'			=> 'Status',
    'tag'				=> 'Asset Tag',
    'update'			=> 'Asset Update',
    'warranty'			=> 'Warranty',
	'warranty_expires'	=> 'Warranty Expires',
    'years'				=> 'years',
)
;
